services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: lirgat/devops-for-developers-project-74:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
