setup:
	npm install --ignore-scripts

test:
	npm test

dev:
	npm run dev

start-frontend:
	npm run start-frontend

start-backend:
	npm run start-backend

.PHONY: setup test dev start-frontend start-backend
