setup:
	npm install --ignore-scripts --no-optional

migrate:
	npx sequelize db:migrate

start:
	npm run start

dev:
	npm run dev

build:
	npm run build

test:
	npm test

.PHONY: setup migrate start dev build test
